---
title: "final project model"
author: "Andres Felix"
output: html_document
date: "2024-01-23"
---


```{r}
library("tidymodels")
library('readr')
library('randomForest')
library('tidyverse')

```



```{r}
apartments_for_rent_classified_10K <- read_delim("Downloads/apartment+for+rent+classified (1)/apartments_for_rent_classified_10K.csv", 
     delim = ";", escape_double = FALSE, trim_ws = TRUE)

apartments_data =  apartments_for_rent_classified_10K 

view(apartments_data)

glimpse(apartments_data)




```

```{r}
apt_df <- 
  apartments_data %>%  
  mutate(pets_allowed = 
           fct_recode(pets_allowed,  
                      "No" = "null",
                      "No" = "None",
                      "Yes"= "Cats,Dogs",
                      "Yes"= "Cats",
                      "Yes"= "Dogs"))
apartments_data <- 
  apartments_data %>%  
  mutate(bathrooms = 
           fct_recode(bathrooms,  
                      "0" = "null",))

apt_df <- apartments_data %>% as_tibble() %>% 
  mutate(pets_allowed = as.factor(pets_allowed),
         bathrooms = as.factor(bathrooms),
         bedrooms = as.factor(bedrooms)) %>% 
  mutate_if(is.character, as.factor) %>% select(-address, -source, -body, -title, -id, -category, -has_photo, -price_type, -time, -latitude, -longitude, -price,-fee, -currency, - amenities)
library('partykit')


# view(apt_df)

apt_preds <- apt_df %>% rownames_to_column() %>% 
  mutate(rowname = as.numeric(rowname))

B <- 5      # number of bootstrap samples
num_b <- 10  # sample size of each bootstrap
boot_mods <- list() # store our bagging models
for(i in 1:B)
  boot_idx <- sample(1:nrow(apt_df), 
                     size = num_b,
                     replace = FALSE)


# clean data by creating a binary variable of "survived" vs "did not survive"
# create factors for sex and class of cabin

apt_df <- apt_df %>% as_tibble() %>% 
  mutate(pets_allowed = as.factor(pets_allowed),
         bedrooms = as.numeric(bedrooms),
         bathrooms = as.numeric(bathrooms),
         price_display= as.numeric(price_display)) %>% 
  mutate_if(is.character, as.factor) 

# store rownames as columns
apt_preds <- apt_df %>% rownames_to_column() %>% 
  mutate(rowname = as.numeric(rowname))

  tree <- ctree(pets_allowed ~ bathrooms + square_feet + bedrooms, 
                     data = apt_df %>% drop_na())

B <- 100      # number of bootstrap samples
num_b <- 500  # sample size of each bootstrap
boot_mods <- list() # store our bagging models

for(i in 1:B){
  
  boot_idx <- sample(1:nrow(apt_df), 
                     size = num_b,
                     replace = FALSE)
  # view(apt_df)
  # fit a tree on each bootstrap sample
  
  boot_tree3 <- ctree(pets_allowed ~ bathrooms + bedrooms, 
                     data = apt_df %>% 
                       drop_na() %>% mutate(bathrooms = as.factor(bathrooms),
                                            bedrooms = as.factor(bedrooms))) 

  # store bootstraped model
 
   boot_mods[[i]] <- boot_tree3
  # generate predictions for that bootstrap model
  preds_boot <- data.frame(
    preds_boot = predict(boot_tree3),
    rowname = boot_idx 
  )  
  # rename prediction to indicate which boot iteration it came from
  names(preds_boot)[1] <- paste("preds_boot",i,sep = "")
  # merge predictions to dataset
  apt_preds <- left_join(x = apt_preds, y = preds_boot,
                                  by = "rowname")
}

plot(boot_tree3)
print(boot_tree3)
## examine some of the individual models

plot(boot_mods[[1]], gp = gpar(fontsize = 8))

plot(boot_mods[[10]], gp = gpar(fontsize = 6))

plot(boot_mods[[50]], gp = gpar(fontsize = 6))

# must convert factor into numeric, note that class "0" = 1, 
# and class "1" = 2, so we need to subtract 1 from every column
apt_preds %<>% mutate_if(is.factor, as.numeric) %>% 
  mutate_all(function(x){x - 1})

# calculate mean over all the bootstrap predictions
apt_preds <- apt_preds %>% drop_na() %>% 
  mutate(apt_preds = 
           select(preds_boot) %>% 
           rowMeans(na.rm = TRUE))
                       

# congratulations! You have bagged your first model!
ggplot(apt_preds, aes(x = apt_preds)) + 
  geom_histogram()





plot(boot_tree3)
```



```{r}
# clean data by creating a binary variable of "survived" vs "did not survive"
# create factors for sex and class of cabin
apt_df <- apartments_data %>% as_tibble() %>% 
  mutate(pets_allowed = as.factor(pets_allowed),
         bathrooms = as.factor(bathrooms),
         bedrooms = as.factor(bedrooms)) %>% 
  mutate_if(is.character, as.factor) %>% 
  select(-address, -source, -body, -title, -id, -category, -has_photo, -price_type, -time, -latitude, -longitude, -price,-fee, -currency, - amenities)


library(partykit)

# view(apt_df)
# store rownames as columns
apt_preds <- apt_df %>% rownames_to_column() %>% 
  mutate(rowname = as.numeric(rowname))

# view(apt_preds)

B <- 10      # number of bootstrap samples
num_b <- 50  # sample size of each bootstrap
boot_mods <- list() # store our bagging models
 for(i in 1:B){
  boot_idx <- sample(1:nrow(apt_df), 
                     size = num_b,
                     replace = FALSE)
  # fit a tree on each bootstrap sample
  
  boot_tree4 <- ctree(pets_allowed ~ bedrooms + bathrooms + price_display , 
                     data = apt_df %>% 
                       slice(boot_idx)) 
  # store bootstraped model
  boot_mods[[i]] <- boot_tree4
  # generate predictions for that bootstrap model
  preds_boot <- data.frame(
    preds_boot = predict(boot_tree4),
    rowname = boot_idx 
  )  
  # rename prediction to indicate which boot iteration it came from
  names(preds_boot)[1] <- paste("preds_boot",i,sep = "")
  # merge predictions to dataset
  apt_preds <- left_join(x = apt_preds, y = preds_boot,
                                  by = "rowname")
 }
 boot_tree4 <- ctree(pets_allowed ~ bedrooms + bathrooms + price_display, 
                   data = apt_df %>% 
                     slice(boot_idx)) 

# store bootstraped model
boot_mods[[i]] <- boot_tree4  # Use the model fitted in the current iteration
# generate predictions for that bootstrap model
preds_boot <- data.frame(
  preds_boot = predict(boot_tree4),
  rowname = boot_idx 
)  
# view(apt_df)

boot_tree4 <- ctree(pets_allowed ~ bedrooms + bathrooms + price_display, 
                   data = apt_df %>% 
                     slice(boot_idx)) 

# store bootstraped model
boot_mods[[i]] <- boot_tree4  # Use the model fitted in the current iteration
# generate predictions for that bootstrap model
preds_boot <- data.frame(
  preds_boot = predict(boot_tree4),
  rowname = boot_idx 
)  


## examine some of the individual models
plot(boot_mods[[1]], gp = gpar(fontsize = 8))

plot(boot_mods[[10]], gp = gpar(fontsize = 6))

plot(boot_mods[[50]], gp = gpar(fontsize = 6))

# must convert factor into numeric, note that class "0" = 1, 
# and class "1" = 2, so we need to subtract 1 from every column
apt_preds %<>% mutate_if(is.factor, as.numeric) %>% 
  mutate_all(function(x){x - 1})

# calculate mean over all the bootstrap predictions
head(apt_preds)

apt_preds <- apt_preds %>% 
  mutate(preds_bag = 
           select(., preds_boot10:preds_boot100) %>% 
           rowMeans(na.rm = TRUE))

# congratulations! You have bagged your first model!
ggplot(titanic_boot_preds, aes(x = preds_bag)) + 
  geom_histogram()
```


```{r}
plot(rf_fit_apt)
```
  
```{}

library('randomForest')


rf_fit <- randomForest(pets_allowed ~ 
                         bathrooms + bedrooms + price_display + 
                         square_feet, 
                       data = apt_df,
                       type = classification,
                       mtry = 3,
                       na.action = na.roughfix,
                       ntree = 400, 
                       importance = TRUE)

print(rf_fit)

plot(rf_fit)

# Tuning Random Forests To Determine
#  Optimal Parameters (mtry)
#---------------------------------------------------------------
rf_mods <- list()
oob_err <- NULL
test_err <- NULL
for(mtry in 1:9){
  rf_fit <- randomForest(Survived ~ 
                           Pclass + Sex + Age + SibSp + Fare, 
                         data = titanic_df,
                         mtry = mtry,
                         na.action = na.roughfix,
                         ntree = 600)
  oob_err[mtry] <- rf_fit$err.rate[600]
  
  cat(mtry," ")
}

results_DF <- data.frame(mtry = 1:9, oob_err)
ggplot(results_DF, aes(x = mtry, y = oob_err)) + geom_point() + theme_minimal()

```
  
  # Create a random dataset
data <- rnorm(1000)

# Create a histogram
hist(apt_df, 
     main = "Pets Allowed per room",  
     xlab = "apt_df$bathrooms",         
     ylab = "apt_df$pets_allowed",         
     col = "skyblue",             
     border = "black",            
     breaks = 20)           
     
ggplot(data = apartments_data, aes(pets_allowed, bathrooms)) + geom_histogram()

# Add additional customization if needed

  
  
  